# arb-dir: lib/l10n/arb
# template-arb-file: intl_en.arb
# output-localization-file: app_localizations.dart
# synthetic-package: false
# output-dir: lib/l10n/src
# use-escaping: true
# nullable-getter: false

# flutter gen-l10n