name: shenbagakutty_vagaiyara
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
  flutter_local_notifications: ^18.0.1
  open_file: ^3.5.10
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  iconsax: ^0.0.8
  http: ^1.2.2
  firebase_messaging: ^15.1.4
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  package_info_plus: ^8.1.1
  flutter_svg: ^2.0.14
  open_app_settings: ^2.0.1
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_exif_rotation: ^0.5.2
  path: ^1.9.0
  syncfusion_flutter_calendar: ^27.2.2
  syncfusion_flutter_pdfviewer: ^27.2.2
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  localstore: ^1.4.0
  qr_flutter: ^4.1.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: normal